# GPT 실습

220604

GPT huggingface 사용법, few-shot learning, chatbot

In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.2 MB 29.7 MB/s 
     |████████████████████████████████| 86 kB 6.5 MB/s 
     |████████████████████████████████| 596 kB 57.2 MB/s 
     |████████████████████████████████| 6.6 MB 59.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
import torch
from transformers import GPT2Config, GPT2LMHeadModel, GPT2TokenizerFast

plm = 'skt/kogpt2-base-v2'

In [4]:
config = GPT2Config.from_pretrained(plm)
print(config)

Downloading:   0%|          | 0.00/0.98k [00:00<?, ?B/s]

GPT2Config {
  "_num_labels": 1,
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "author": "Heewon Jeon(madjakarta@gmail.com)",
  "bos_token_id": 0,
  "created_date": "2021-04-28",
  "embd_pdrop": 0.1,
  "eos_token_id": 1,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0"
  },
  "initializer_range": 0.02,
  "label2id": {
    "LABEL_0": 0
  },
  "layer_norm_epsilon": 1e-05,
  "license": "CC-BY-NC-SA 4.0",
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "pad_token_id": 3,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample":

In [5]:
model = GPT2LMHeadModel.from_pretrained(plm, config=config)
print(model)

Downloading:   0%|          | 0.00/490M [00:00<?, ?B/s]

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(51200, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dro

In [6]:
tokenizer = GPT2TokenizerFast.from_pretrained(plm, bos_token='<s>', eos_token='</s>', unk_token='<unk>')

Downloading:   0%|          | 0.00/2.69M [00:00<?, ?B/s]

In [7]:
text = '근육이 커지기 위해서는'

In [8]:
# tokenize: string -> subword
subwords = tokenizer.tokenize(text)
print(subwords)
# convert_tokens_to_ids: subword -> id
input_ids = tokenizer.convert_tokens_to_ids(subwords)
print(input_ids)

['▁근육이', '▁커', '지기', '▁위해서는']
[33245, 10114, 12748, 11357]


In [9]:
# encode: string -> id
input_ids = tokenizer.encode(text)
print(input_ids)

[33245, 10114, 12748, 11357]


In [10]:
gen_ids = model.generate(torch.tensor([input_ids]),
                         max_length=128,
                         repetition_penalty=2.0,
                         eos_token_id=tokenizer.eos_token_id,
                         bos_token_id=tokenizer.bos_token_id)
print(gen_ids)

tensor([[33245, 10114, 12748, 11357, 23879, 39306,  9684,  7884, 10211, 15177,
         26421,   387, 17339,  7889,  9908, 15768,  6903, 15386,  8146, 12923,
          9228, 18651, 42600,  9564, 17764,  9033,  9199, 14441,  7335,  8704,
         12557, 32030,  9510, 18595,  9025, 10571, 25741, 10599, 13229,  9508,
          7965,  8425, 33102,  9122, 21240,  9801, 32106, 13579, 12442, 13235,
         19430,  8022, 12972,  9566, 11178,  9554, 24873,  7198,  9391, 12486,
          8711,  9346,  7071, 36736,  9693, 12006,  9038, 10279, 36122,  9960,
          8405, 10826, 18988, 25998,  9292,  7671,  9465,  7489,  9277, 10137,
          9677,  9248,  9912, 12834, 11488, 13417,  7407,  8428,  8137,  9430,
         14222, 11356, 10061,  9885, 19265,  9377, 20305,  7991,  9178,  9648,
          9133, 10021, 10138, 30315, 21833,  9362,  9301,  9685, 11584,  9447,
         42129, 10124,  7532, 17932, 47123, 37544,  9355, 15632,  9124, 10536,
         13530, 12204,  9184, 36152,  9673,  9788,  

In [11]:
generated = tokenizer.decode(gen_ids[0].tolist())
print(generated)

근육이 커지기 위해서는 무엇보다 규칙적인 생활습관이 중요하다.
특히, 아침식사는 단백질과 비타민이 풍부한 과일과 채소를 많이 섭취하는 것이 좋다.
또한 하루 30분 이상 충분한 수면을 취하는 것도 도움이 된다.
아침 식사를 거르지 않고 규칙적으로 운동을 하면 혈액순환에 도움을 줄 뿐만 아니라 신진대사를 촉진해 체내 노폐물을 배출하고 혈압을 낮춰준다.
운동은 하루에 10분 정도만 하는 게 좋으며 운동 후에는 반드시 스트레칭을 통해 근육량을 늘리고 유연성을 높여야 한다.
운동 후 바로 잠자리에 드는 것은 피해야 하며 특히 아침에 일어나면 몸이 피곤해지기 때문에 무리하게 움직이면 오히려 역효과가 날 수도 있다.
운동을


In [12]:
def gpt_inference(prompt='근육이 커지기 위해서는'):
    with torch.no_grad():
        # tokenize: string -> subword -> id
#         subwords = tokenizer.tokenize(prompt)        
#         input_ids = tokenizer.convert_tokens_to_ids(subwords)
        # encode: string -> id
    
        ## 1_tokenize
        input_ids = tokenizer.encode(prompt)
        print('#'*40)
        print('1_tokenize\n%s\n  => %s'%(prompt, input_ids))        
        
        ## 2_Generate gpt-inference
        gen_ids = model.generate(torch.tensor([input_ids]),
                                 max_length=128,
                                 repetition_penalty=2.0,
                                 eos_token_id=tokenizer.eos_token_id,
                                 bos_token_id=tokenizer.bos_token_id)
        print('#'*40)
        print('2_generate\n%s'%(gen_ids))              
        
        ## 3_Detokenize        
        generated = tokenizer.decode(gen_ids[0].tolist())
        print('#'*40)
        print('3_Detokenize\n%s'%(generated))             
        
    return generated

In [13]:
generate_text = gpt_inference(prompt='도메인 특화 자연어처리 모델을 개발하기 위해서는')

########################################
1_tokenize
도메인 특화 자연어처리 모델을 개발하기 위해서는
  => [48088, 8148, 9125, 8756, 9632, 8006, 14402, 47559, 40468, 11357]
########################################
2_generate
tensor([[48088,  8148,  9125,  8756,  9632,  8006, 14402, 47559, 40468, 11357,
         13753,  8263,  7166, 13703,   415,   384, 11217,  8143,  9772,   422,
           426,  7470, 10804,  9685, 11402, 20899, 12500, 14465, 11675, 25608,
          9830, 10003,   417, 24054,   410,  9634, 12199,  7187, 15179,  9563,
         16858,  7244,  9741,  8023, 17698, 13363,  9194, 10470, 10559, 12767,
         18420, 13472, 20953,  9018,  9239, 12891,  9417, 35137, 15405,  8146,
          7623, 37921, 11196,   407, 24645,  6824, 21073,  9038,  9426, 11277,
          8170, 11016, 14996,  9062,  8056,  8711, 11570,  9052, 10040, 19760,
          9425,  8703,  9140,  9464, 10274, 24609,  9030,  9246, 29763, 10378,
         49864,  6963,  8042,  7889,  9076, 10201, 10063, 13335, 11280, 10875,
        

In [14]:
prompt = """
Q:질문내용 여기에 입력하세요
A:"""
generate_text = gpt_inference(prompt=prompt)

########################################
1_tokenize

Q:질문내용 여기에 입력하세요
A:
  => [9051, 423, 401, 8267, 7559, 9336, 11944, 27318, 8702, 7801, 12002, 407, 401]
########################################
2_generate
tensor([[ 9051,   423,   401,  8267,  7559,  9336, 11944, 27318,  8702,  7801,
         12002,   407,   401,  8146,  7623,  8236, 10164, 25483,  9148,  9285,
          8084, 10665,   739,  9168,   375,  8149,  7185, 10070,  8135, 45887,
         22600,  9228, 12191, 11725,  8711,  7281,  7481,  6866, 10078, 37767,
         19787,  7489, 12011,  9867,  9265,  7162,  9018, 18554,  9609, 33146,
         12399, 10278,  9950, 11814,  8718, 10010,  8066,  8148,  9383, 12341,
         26099, 10586,  9362,  9320, 50273, 11686, 41190,  9445,  9199, 29205,
         11355,  8155, 10247, 12371,  9677,  7978, 14782, 19561,  7788, 22301,
          9046,  9052, 12642, 15354,  9535,  7810,  7652,  7888,  6962, 23429,
         31814,  8185,  7235,  9443, 42138,  9176, 22126,  8022,  9564,  7285,
  

In [15]:
prompt = """
오늘은 텍스트 생성 모델 GPT에게 향후 자연어처리 공부방법에 대해 물어보겠습니다
Q: 인공지능 자연어처리 수업에 오신걸 환영합니다.
A: """
generate_text = gpt_inference(prompt=prompt)

########################################
1_tokenize

오늘은 텍스트 생성 모델 GPT에게 향후 자연어처리 공부방법에 대해 물어보겠습니다
Q: 인공지능 자연어처리 수업에 오신걸 환영합니다.
A: 
  => [9051, 30899, 8135, 17566, 9581, 11916, 14652, 10528, 422, 426, 9134, 14323, 9632, 8006, 14402, 11018, 29851, 9552, 27515, 7652, 6872, 16913, 9503, 423, 401, 13753, 8263, 7166, 9632, 8006, 14402, 15328, 8022, 9114, 7890, 6857, 30721, 11387, 407, 401, 739]
########################################
2_generate
tensor([[ 9051, 30899,  8135, 17566,  9581, 11916, 14652, 10528,   422,   426,
          9134, 14323,  9632,  8006, 14402, 11018, 29851,  9552, 27515,  7652,
          6872, 16913,  9503,   423,   401, 13753,  8263,  7166,  9632,  8006,
         14402, 15328,  8022,  9114,  7890,  6857, 30721, 11387,   407,   401,
           739,  7299,  7397,  7180,  8137,  9430, 12384,  8704, 10172, 11420,
          9772,   415,  6824, 10854, 41306,  9337,  9025, 10517, 14355,  8241,
          9361,  8146, 10431, 12442, 19107, 24743, 10239, 16916,  7235,  9826,
  

# 2_DialoGPT-small 실습

GPT를 chatbot 형태로 학습

[URL](https://huggingface.co/microsoft/DialoGPT-small)

In [16]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-small")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-small")

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/641 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/335M [00:00<?, ?B/s]

In [ ]:
from transformers import pipeline, Conversation, AutoTokenizer
print('start')
generator = pipeline('conversational', model='microsoft/DialoGPT-small')  # pipeline에서 conversational을 체크하고 모델을 입력하자
for idx in range(3):
    usertext = input(">> User:")
    conversation = Conversation(usertext)

    output = generator(
        conversation, pad_token_id=tokenizer.eos_token_id).generated_responses

    print(">> Bot: %s"%(output))

start


In [18]:
for turn in range(3):
    usertext = input(">> User:")
    
    # encode the new user input, add the eos_token and return a tensor in Pytorch
    new_user_input_ids = tokenizer.encode(usertext + tokenizer.eos_token, return_tensors='pt')    

    # append the new user input tokens to the chat history
    # 문맥을 반영하기 위해 history 대화도 같이 묶어준다
    bot_input_ids = torch.cat([chat_history_ids, new_user_input_ids], dim=-1) if turn > 0 else new_user_input_ids    

    # generated a response while limiting the total chat history to 1000 tokens, 
    # 글을 생성하고 decode 한다
    chat_history_ids = model.generate(bot_input_ids, max_length=1000, pad_token_id=tokenizer.eos_token_id)        
    chat_history = tokenizer.decode(chat_history_ids[0]).split("<|endoftext|>")

    # pretty print last ouput tokens from bot
    # 마지막 생성한 응답만 짤라서 출력한다    
    chat_history = [(chat_history[i], chat_history[i+1]) for i in range(0, len(chat_history)-1, 2)]  # convert to tuples of list    
    response = chat_history[-1][1]

    print(">> Bot: {}\nhistory:{}".format(response, chat_history))



>> User:Good morning?
>> Bot: Good morning!
history:[('Good morning?', 'Good morning!')]
>> User:It's actually nigh 
>> Bot: Good morning!
history:[('Good morning?', 'Good morning!'), ("It's actually nigh ", 'Good morning!')]
>> User:Have a good daytt
>> Bot: I'm good.
history:[('Good morning?', 'Good morning!'), ("It's actually nigh ", 'Good morning!'), ('Have a good daytt', "I'm good.")]
